[package]
name = "sync"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
ws = "0.9.1"
mio = "0.6.19"
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.41"
enum_dispatch = "0.2.0"

[dev-dependencies]
maplit = "1.0"
portpicker = "0.1.0"
websocket-lite = "0.3.0-alpha.6"
better-panic = "0.2.0"